---
name: PHP

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  psalm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Psalm – Static Analysis for PHP
      # You may pin to the exact commit or the version.
      # uses: psalm/psalm-github-actions@2e545d38ff4387b370449e2673088cc8dc40cf1d
      uses: psalm/psalm-github-actions@1.1.2
      #with:
        # Whether or not to use Psalm’s security analysis
        #security_analysis: # optional
        # File for Psalm’s output
        #report_file: # optional, default is
        # Whether or not Composer installs dev packages
        #composer_require_dev: # optional
        # Whether or not the --ignore-platform-reqs flag is passed to Composer
        #composer_ignore_platform_reqs: # optional

  phpcs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: php-codesniffer
      uses: pipeline-components/php-codesniffer@v0.12.3

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@b7d1d9c9a92d8d8463ce36d7f60da34d461724f8
      with:
        php-version: '7.4'
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
